const cmp_names = {
  2: 'Chandago',
  3: 'Faktor BV',
  5: 'Usercentrics GmbH',
  6: 'Sourcepoint Technologies, Inc.',
  7: 'Didomi',
  8: 'Baycloud Systems Limited',
  9: 'Admiral',
  10: 'Quantcast International Limited',
  11: 'Sovrn Holdings Ince',
  12: 'Germantag Web Services',
  13: 'Databoxer Limited',
  14: 'Oath (EMEA) Limited',
  15: 'Cookie Trust Working Group, Inc.',
  18: 'Evidon, Inc',
  19: 'Adform A/S',
  20: 'Skimbit Ltd',
  21: 'Traffective GmbH',
  23: 'Conversant Europe Ltd.',
  25: 'ShareThis, Inc.',
  26: 'Predesto, Inc.',
  27: 'Associated Newspapers Ltd',
  28: 'OneTrust LLC',
  29: 'Captify Technologies Limited',
  30: 'Rich Audience International SL',
  31: 'consentmanager.net ',
  32: 'Unveilmedia Ltd',
  33: 'Smart Adserver',
  34: 'Acxiom Corporation',
  35: 'BurdaForward GmbH',
  36: 'RTB House S.A.',
  37: 'Vibrant Media Limited',
  38: 'System1 LLC',
  39: 'Sortable',
  40: 'Purch Group, Inc.',
  41: 'Grupa Netsprint Sp z o.o.',
  43: 'Crimtan Holdings Limited',
  44: 'Madvertise Media',
  45: 'Ogury Ltd',
  46: 'Mediavine, Inc.',
  47: 'TrustArc Inc',
  48: 'Adlive Technology',
  49: 'Sanoma Media Finland Oy',
  50: 'ETARGET SE',
  51: 'smartclip Holding AG',
  52: 'Media IQ Digital Ltd',
  53: 'Consent System Ltd',
  54: 'AdRoll, Inc',
  55: 'Triboo Media SRL',
  57: 'WEBEDIA',
  58: 'Ciao people s.r.l.',
  59: 'Deezer',
  60: 'Rossel Advertising CMP',
  61: 'Spolecznosci Sp. z o.o. Sp.k.',
  62: 'Gumtree.com Ltd',
  63: 'ALZ Software Ltd (trading as Clickio)',
  64: 'ProSiebenSat.1 Digital Data GmbH',
  65: 'OneTag Ltd',
  66: 'Yieldlab AG',
  68: 'Transfon Ltd',
  69: 'Gremi Media SA',
  71: 'Edipresse Polska S.A.',
  72: 'Wirtualna Polska Media S.A.',
  74: 'Relevant Digital Oy',
  75: 'VECTAURY',
  76: 'SIBBO VENTURES SLU',
  77: 'Teaching Aids, LLC',
  78: 'Ezoic Inc.',
  79: 'SFR',
  80: 'Axel Springer SE',
  81: 'Otavamedia Oy',
  82: 'AdTech Factory GmbH & Co. KG',
  83: 'Prisa Brand Solutions, S.L.U',
  84: 'Alma Media',
  85: 'SIPA',
  86: 'Nouw Media AB',
  87: 'Tappcelerator Media SL',
  88: 'Apester Ltd',
  89: 'Valnet Inc.',
  90: 'Commanders Act',
  92: 'SIRDATA',
  93: 'Global Radio Services Ltd',
  94: 'MOTDgd Ltd',
  96: 'Triboo Data Analytics',
  97: 'HIRO Media Ltd',
  98: 'predict.io GmbH',
  99: 'GDPR-SDK',
  100: 'Cambium Media',
  101: 'Eulerian Technologies',
  102: 'GDPR Consult Plc',
  103: 'Serinus42 B.V.',
  104: 'Gemius SA',
  105: 'DAILYMOTION SA',
  108: 'Trunomi',
  111: 'Vinted UAB',
  112: 'Guardian News and Media',
  113: 'Grand Play Media, LLC',
  114: 'Adversal Media, Inc.',
  115: 'A-lehdet Oy',
  116: 'Location Sciences AI Ltd',
  118: 'Sonobi, Inc.',
  119: 'Curiosity Media, Inc.',
  120: 'BlueConic',
  121: 'Proper Media, LLC',
  122: 'Web Financial Group S.A./Vortex',
  123: 'iubenda',
  124: 'LIQWID',
  125: 'eBay Inc',
  126: 'B2B Media Group GmbH',
  127: 'AddApptr GmbH',
  128: 'KnowNow Information',
  129: 'Adevinta Spain S.L.U.',
  131: 'Oriel Ventures',
  132: 'Taboola Europe Limited',
  134: 'Cookiebot',
  135: 'calcioinfinito srl',
  136: 'M6 Web',
  139: 'Improve Digital International BV',
  141: 'Wikia, Inc. (FANDOM)',
  142: 'Genius Sports Group Limited',
  143: 'Microsoft Advertising',
  145: 'Car&Boat Media',
  146: 'Tamoco Limited',
  147: 'Car&Boat Media',
  148: 'Car&Boat Media',
  149: 'Car&Boat Media',
  152: 'Teavaro Limited',
  153: 'Avocet Systems Limted',
  155: 'Right Match Media Ltd',
  157: 'YOC AG',
  161: 'Innity',
  162: 'Cookie Information APS',
  163: 'Centro, Inc.',
  164: 'SOCIETE SAS',
  165: 'Bidstack Limited',
  167: '1&1 Mail & Media GmbH',
  168: 'Outlook.com - Microsoft Corporation',
  169: 'Mappy',
  170: 'AGORA SA',
  171: 'Viber Media sarl',
  172: 'Orange SA',
  173: 'Planet Media',
  174: 'Groupe Sud Ouest',
  175: 'Glob 360 Sp. z o.o.',
  177: 'AuFeminin',
  178: 'PRESSIMMO ON LINE',
  179: 'Teads SA',
  180: 'Admetrics GmbH',
  181: 'Marfeel Solutions S.L ',
  182: 'StreamAMP Ltd ',
  183: 'Sub2 Technologies Ltd ',
  184: 'ASK.FM EUROPE LIMITED',
  185: 'Playwire LLC',
  186: 'Venatus Media Limited',
  187: 'Livesport Media Ltd.',
  188: 'ADN CONTENTS',
  190: 'Fidzup ',
  191: 'Piwik PRO Sp. z o.o.',
  193: 'RTP SA',
  194: 'Spil Games B.V.',
  195: 'Totaljobs Group Ltd',
  196: 'Newsroom AI Ltd.',
  197: 'Publy ltd',
  198: 'Microsoft Casual Games',
  199: 'Grindr LLC',
  200: 'Syrenis',
  201: 'AgeCheq, Inc. dba PrivacyCheq',
  203: 'X-Mode Social, Inc.',
  204: 'Destino',
  205: 'Bit Q Holdings Limited ',
  206: 'PAGESJAUNES',
  207: 'willhaben',
  208: 'Golden Bees',
  209: 'LifeStreet Corporation',
  210: 'Red Pineapple Media GmbH',
  212: 'Singlespot ',
  213: 'Clym Ltd. ',
  214: 'LBC France',
  215: 'Smartclip Hispania S.L. ',
  216: 'Listonic sp. z o. o.',
  217: 'BMIND SALES MAKER COMPANY S.L. ',
  218: 'RCS MediaGroup S.p.A.',
  219: 'Nielsen Marketing Cloud',
  220: 'Allegro.pl Sp z o.o.',
  221: 'Dentsu Aegis Network Germany GmbH',
  222: 'ParuVendu.fr',
  223: 'Gedi Digital s.r.l.',
  224: 'Ensighten, Inc',
  225: 'Internetowy Dom Mediowy net S.A.',
  226: 'Società Athesis S.p.A.',
  227: 'Healthline Media, Inc.',
  228: 'Thirdfloor SRL',
  229: 'Snigel Web Services Limited ',
  231: 'Grupa Interia.pl Sp. z o.o. sp. k.',
  233: 'M32 Media Inc.',
  235: 'Adnuntius AS',
  236: 'WebAds B.V',
  237: 'ALPRED SL',
  238: 'Yieldbird Sp. z o.o.',
  240: 'Network N Ltd',
  241: 'CafeMedia/AdThrive',
  242: 'GG Software, LLC',
  244: 'Livingly Media',
  245: 'Onefootball GmbH',
  246: 'Overwolf Ltd.',
  247: 'Seznam.cz, a.s.',
  252: 'MAIRDUMONT NETLETIX GmbH&Co. KG',
  256: 'AdMatic Medya AS',
  258: 'Automattic, Inc.',
  262: 'TrueData Solutions, Inc.',
  264: 'Secure Privacy',
  265: 'ADVFN PLC',
  268: 'Pharma Partner sp. z o.o.',
  273: 'Next14 SpA',
  274: 'Aller Media',
  280: 'Ringier Axel Springer Polska',
  281: 'PubNative GmbH',
  282: 'Farlex Inc',
  291: 'Consent Desk LLC',
  292: 'Blasting SA',
};
